apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-clusterrole-binding
subjects:
- kind: Group
  name: manager # name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  name: my-clusterrole-binding
  apiGroup: rbac.authorization.k8s.io
  
