apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-role
  labels:
  - role: user-role
  namespace: default
rules:
- apiGroups: [""] # "" indicate the core api Group
  resources: ["pods", "pods/log"]
  verbs: ["get", "watch", "list"]