apiVersion: v1
kind: Pod
metadata:
  name: volume-demo
spec:
  containers:
  - name: my-pod
    image: nginx.1.19
    volumeMounts:
    - name: my-volume
      mountPath: /output
    
  volumes:
  - name: my-volume
    hostPath:
      path: /data

